title: Arjun Ghoshal CSE 15L
description: Arjun Ghoshal's website for CSE 15L labs and lab reports
theme: jekyll-theme-slate
url: 'https://arjunghoshal.github.io/cse15l-lab-reports'
baseurl: '/cse15l-lab-reports'